### ISSUE TITLE
Wrong `GeneratedZoneIdsProvider` included in published artifact

### ISSUE THREAD

**Issue by mateuszkwiecinski** [gabrielittner/lazythreetenbp#125]
Hey 👋 
I wasn't sure if the library is still maintained so I allowed myself to [fork](https://github.com/usefulness/lazythreetenbp) it and adjust it to my needs and I think I spotted an issue you should be aware of. It seems like the published artifact contains `GeneratedZoneIdsProvider` which comes from sources: https://github.com/gabrielittner/lazythreetenbp/blob/4fb246cfda99892133f0bcb154d7e75609048a27/runtime/src/main/java/com/gabrielittner/threetenbp/GeneratedZoneIdsProvider.java#L10
not the one generated by ticktock plugin under `generated/ticktock` 🤔 

Here's how the diff looks like:
![image](https://user-images.githubusercontent.com/36954793/160256998-5e001969-ca5d-4c3e-81a8-7243ba4a0ca9.png)
doesn't seem significant, but it felt like worth reporting here. It isn't intended, right?

**Comment by gabrielittner** [comment]
Sorry for the late reply I missed the email. This wasn't intended and is fixed in version 0.11.0
