### ISSUE TITLE
Consider using `api` dependency on ThreeTenBP

### ISSUE THREAD

**Issue by chrisbanes** [gabrielittner/lazythreetenbp#13]
I'm using a library in my app which has a dependency on `org.threeten:threetenbp:1.3.4`. After adding LazyThreeTenBP, my build broke with: 

`Error:com.android.builder.merge.DuplicateRelativeFileException: More than one file was found with OS independent path 'org/threeten/bp/format/ChronologyText.properties'`

After investigating, it seems that LazyThreeTenBP has a compile dependency on treetenbp's `no-tzdb` artifact, which breaks my dependency resolution and results in both artifacts being bundled. I can easily fix this by excluding that library's dependency, but it might be nicer if LazyThreeTenBP had an `api` dependency on ThreeTenBP instead, and relied on the app to depend on it explicitly.

**Comment by gabrielittner** [comment]
What's your reason for depending on the regular threetenbp artifact instead of the no-tzdb one? You'll get two timezone databases in your apk this way.

**Comment by chrisbanes** [comment]
I don't control the original dependency, it depends on the normal artifact. Since you provide the tzdbs in `:runtime` this isn't actually feasible. I'll just keep my `exclude` :+1:

**Comment by lahiru04** [comment]
how did you exclude it?
