### ISSUE TITLE
Investigate performance impact of unused threetenbp ServiceLoader

### ISSUE THREAD

**Issue by gabrielittner** [gabrielittner/lazythreetenbp#2]
`org.threeten.bp.zone.ZoneRulesProvider` tries to load available providers using `ServiceLoader` in a static initializer block. That's not needed on Android. From some quick measurements costs up to 20ms for doing nothing. The measurement was done by calling `ZoneRulesProvider.getAvailableZoneIds()` before the tz initialization (the method itself is basically a no-op in that case but triggers the block).

https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/zone/ZoneRulesProvider.java#L84

**Comment by mmallozzi** [comment]
https://github.com/ThreeTen/threetenbp/issues/63

On my fairly low-end device (HTC Desire 526), our application onCreate method was slowed down by 200ms using this library as is, vs. 77ms using a build of this library that was forced to use a local build of threetenbp which strips out the static initializer block from ZoneRulesProvider.

**Comment by gabrielittner** [comment]
Closing this because Matt confirmed that ServiceLoader has a huge impact. For follow ups see the linked threetenbp issue.
